---
- name: Install base packages
  ansible.builtin.apt: 
    name: "{{ base_packages }}"
    state: latest
    update_cache: yes
  become: true

- name: Install optional packages (continue on error)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  become: true
  loop: "{{ optional_packages | default([]) }}"
  register: optional_pkg_result
  failed_when: false

- name: Display warning for optional packages that could not be installed
  ansible.builtin.debug:
    msg: "Warning: Optional package {{ item.item }} could not be installed. Continuing."
  loop: "{{ optional_pkg_result.results }}"
  when: item.failed is defined and item.failed

- name: Install Debian-specific packages
  ansible.builtin.apt:
    name: "{{ debian_specific_packages }}"
    state: latest
  become: true
  when: ansible_distribution == 'Debian'

- name: Install Ubuntu-specific packages
  ansible.builtin.apt:
    name: "{{ ubuntu_specific_packages }}"
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Configure apticron
  ansible.builtin.template: 
    src: apticron.conf.j2
    dest: "{{ apticron_conf_path }}"
    owner: root
  become: true
  notify: Restart apticron

- name: Configure fail2ban
  ansible.builtin.template: 
    src: defaults-debian.conf.j2
    dest: "{{ fail2ban_conf_path }}"
    owner: root
  become: true
  notify: Restart fail2ban

- name: Check if Apache is installed
  ansible.builtin.shell: dpkg -l apache2 | grep -q "^ii"
  register: apache_check
  failed_when: false
  changed_when: false

- name: Check if Nginx is installed
  ansible.builtin.shell: dpkg -l nginx | grep -q "^ii"
  register: nginx_check
  failed_when: false
  changed_when: false

- name: Check if MySQL server is installed
  ansible.builtin.shell: dpkg -l mysql-server || dpkg -l mariadb-server
  register: mysql_check
  failed_when: false
  changed_when: false

- name: Check if MySQL filter files exist
  ansible.builtin.stat:
    path: /etc/fail2ban/filter.d/mysqld-auth.conf
  register: mysql_filter_check
  when: mysql_check.rc == 0

- name: Configure fail2ban Apache jails
  ansible.builtin.template:
    src: jail-apache.j2
    dest: /etc/fail2ban/jail.d/apache.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban
  when: apache_check.rc == 0

- name: Configure fail2ban Nginx jails
  ansible.builtin.template:
    src: jail-nginx.j2
    dest: /etc/fail2ban/jail.d/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban
  when: nginx_check.rc == 0

- name: Configure fail2ban MySQL jails
  ansible.builtin.template:
    src: jail-mysql.j2
    dest: /etc/fail2ban/jail.d/mysql.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart fail2ban
  when: mysql_check.rc == 0 and mysql_filter_check.stat.exists

# Import chezmoi tasks from separate file
- name: Setup chezmoi
  ansible.builtin.import_tasks: chezmoi.yaml
  when: chezmoi_install | bool
  tags: chezmoi
