---
- name: Install base packages
  ansible.builtin.apt: 
    name: "{{ base_packages }}"
    state: latest
    update_cache: yes
  become: true

- name: Install optional packages (continue on error)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  become: true
  loop: "{{ optional_packages | default([]) }}"
  register: optional_pkg_result
  failed_when: false

- name: Display warning for optional packages that could not be installed
  ansible.builtin.debug:
    msg: "Warning: Optional package {{ item.item }} could not be installed. Continuing."
  loop: "{{ optional_pkg_result.results }}"
  when: item.failed is defined and item.failed

- name: Install Debian-specific packages
  ansible.builtin.apt:
    name: "{{ debian_specific_packages }}"
    state: latest
  become: true
  when: ansible_distribution == 'Debian'

- name: Install Ubuntu-specific packages
  ansible.builtin.apt:
    name: "{{ ubuntu_specific_packages }}"
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Configure apticron
  ansible.builtin.template: 
    src: apticron.conf.j2
    dest: "{{ apticron_conf_path }}"
    owner: root
  become: true
  notify: Restart apticron

- name: Configure fail2ban
  ansible.builtin.template: 
    src: defaults-debian.conf.j2
    dest: "{{ fail2ban_conf_path }}"
    owner: root
  become: true
  notify: Restart fail2ban

# Import chezmoi tasks from separate file
- name: Setup chezmoi
  ansible.builtin.import_tasks: chezmoi.yaml
  when: chezmoi_install | bool
  tags: chezmoi
