---
  - name: Install packages
    ansible.builtin.apt: 
      name: ['apticron', 'ca-certificates', 'fail2ban', 'duplicity', 'monitoring-plugins', 'postfix', 'htop', 'vim', 'aptitude', 'ntp']
      state: latest
      update_cache: yes
    become: true

  - name: configure apticron
    become: true
    ansible.builtin.template: 
      src: files/apticron.conf 
      dest: /etc/apticron/apticron.conf 
      owner: root

  - name: configure fail2ban
    become: true
    ansible.builtin.template: 
      src: files/defaults-debian.conf 
      dest: /etc/fail2ban/jail.d/defaults-debian.conf 
      owner: root

  - name: restart service fail2ban
    become: true
    ansible.builtin.systemd:
      state: restarted
      name: fail2ban
