---
- name: basic setup sudo
  hosts: debian-based
  vars:
    my_user: "{{ ansible_user }}"
    pbname: $inventory_hostname
    distro: ${ansible_distribution}
    pkg_mgr: ${ansible_pkg_mgr}
    zsh_theme: agnoster
    ssh_keys: https://github.com/andibraeu.keys
  roles:
  - install_sudo
  - add_admin_user
  - copy_ssh_keys
  - install_basic_packages
