---
- name: basic setup sudo
  hosts: debian-based
  vars:
    my_user: "{{ ansible_user }}"
    pbname: $inventory_hostname
    distro: ${ansible_distribution}
    pkg_mgr: ${ansible_pkg_mgr}
    zsh_theme: agnoster
    ssh_keys: https://github.com/andibraeu.keys
    # Defaults – pro Host/Gruppe überschreibbar (host_vars / group_vars)
    # monitor_with_vmagent: Default entfernt, wird über host_vars/group_vars gesetzt
    auto_detect_exporters: true                   # Auto-Erkennung aktiv
    vmauth_url: "https://vmauth.ei.ne-zier.de/api/v1/write"
    # vm_user und vm_pass: werden über host_vars/group_vars pro Host gesetzt
    vm_remote_label: "source={{ inventory_hostname }}"
    # Manuelles Übersteuern (optional)
    enable_apache_exporter: null                  # true/false überschreibt Auto
    enable_bind_exporter:   null
    enable_smartctl_exporter: auto                # true/false überschreibt Auto (nur auf echter Hardware)
    # enable_blackbox_exporter: null                # true/false überschreibt Auto (nur auf externen Monitoring-Servern)
    # node_exporter schlank halten
    node_exporter_disable_defaults: true
    node_exporter_enabled_collectors:
      - cpu
      - meminfo
      - filesystem
      - diskstats
      - netdev
      - loadavg
      - hwmon
      - systemd
      - os
      - textfile
  pre_tasks:
  - name: Check if this is physical hardware (for smartctl)
    ansible.builtin.stat:
      path: /sys/class/block
    register: block_devices_check

  - name: Check for physical block devices (for smartctl)
    ansible.builtin.find:
      paths: /sys/class/block
      patterns: ["sd*"]
      file_type: link
    register: physical_disks
    when: block_devices_check.stat.exists

  - name: Set smartctl hardware detection fact
    ansible.builtin.set_fact:
      has_physical_disks: "{{ physical_disks.matched > 0 }}"


  roles:
  #- install_sudo
  #- add_admin_user
  #- copy_ssh_keys
  #- install_basic_packages
  - role: exporters
    when: monitor_with_vmagent | default(false)
    become: true
  - role: vm_monitoring_agent
    when: monitor_with_vmagent | default(false)
    become: true

