---
- name: Setup NAS for Kubernetes Storage
  hosts: nas  # Host group for NAS systems - add your NAS to the inventory
  become: true
  # All variables are loaded from host_vars/<hostname>/:
  # - host_vars/s54-k3s-nas/vars.yaml (non-sensitive values)
  # - host_vars/s54-k3s-nas/vault.yaml (sensitive, encrypted with ansible-vault)
  #
  # Example structure for host_vars/s54-k3s-nas/vars.yaml:
  #   zfs_pool_name: tank
  #   zfs_k8s_user: zfs-k8s  # Optional: default is zfs-k8s
  #   disable_root_ssh: true  # Optional: disable root login (default: true)
  #   zfs_datasets:
  #     - name: k8s-unencrypted
  #     - name: k8s-encrypted
  #       encryption: true
  #       encryption_algorithm: aes-256-gcm
  #       encryption_keyformat: raw
  #   zfs_dataset_properties:
  #     - dataset: k8s-encrypted
  #       property: quota
  #       value: 2T
  #   nfs_export_path: /tank/k8s-storage
  #   nfs_allowed_networks: 10.0.0.0/8  # or 10.200.0.0/24 for WireGuard-only
  #   nfs_domain: local
  #   wireguard_address: 10.200.0.1/24
  #   wireguard_listen_port: 51820
  #   wireguard_peers:
  #     - name: k3s-node1
  #       public_key: "{{ vault_wg_node1_pubkey }}"
  #       allowed_ips: "10.200.0.11/32"
  #   iscsi_target_iqn: iqn.2024-01.local.s54:k8s-iscsi
  #   iscsi_portal_ip: 0.0.0.0
  #   iscsi_initiator_iqn: iqn.2024-01.local.k3s:*
  #
  # Example structure for host_vars/s54-k3s-nas/vault.yaml:
  #   zfs_datasets_encryption_keys:
  #     k8s-encrypted: "your-32-character-random-key-here"
  #   iscsi_chap_username: k8s
  #   iscsi_chap_password: "your-secure-password"
  #   wireguard_private_key: "NAS_PRIVATE_KEY"
  #   vault_wg_node1_pubkey: "NODE1_PUBLIC_KEY"
  #   vault_wg_node2_pubkey: "NODE2_PUBLIC_KEY"
  #   vault_wg_node3_pubkey: "NODE3_PUBLIC_KEY"
  #
  # Encrypt vault with: ansible-vault encrypt host_vars/s54-k3s-nas/vault.yaml
  # Run playbook with: ansible-playbook setup_nas.yaml -i inventory-s54.yml --ask-vault-pass
  
  pre_tasks:
    - name: Install ZFS utilities (required for pool creation)
      ansible.builtin.apt:
        name:
          - zfsutils-linux
          - zfs-zed
        state: present
        update_cache: true
    
    - name: Check if ZFS pool exists
      ansible.builtin.command: zpool list {{ zfs_pool_name | default('tank') }}
      register: zfs_pool_check
      changed_when: false
      failed_when: false
    
    - name: Show warning if ZFS pool does not exist
      ansible.builtin.debug:
        msg: |
          WARNING: ZFS pool '{{ zfs_pool_name | default("tank") }}' does not exist yet!
          
          After package installation, please create it manually:
          1. Find disk IDs: ls -l /dev/disk/by-id/
          2. Create ZFS pool: zpool create {{ zfs_pool_name | default("tank") }} mirror /dev/disk/by-id/ata-<sda-id> /dev/disk/by-id/ata-<sdb-id>
          
          Optional: Datasets can be created manually OR via Ansible (if zfs_datasets is defined in host_vars).
          
          See README in k3s-deployments/s54/apps/democratic-csi/README.md for details.
      when: zfs_pool_check.rc != 0
  
  roles:
    # ZFS K8s User: Creates dedicated user for Democratic-CSI with sudo rights
    # Disables root SSH login
    - configure_zfs_k8s_user
    
    # ZFS Datasets: Creates datasets and sets properties (quotas, compression, etc.)
    # This role is executed when the pool exists AND:
    # - zfs_datasets is defined (to create datasets) OR
    # - zfs_dataset_properties is defined (to set properties)
    - role: configure_zfs_datasets
      when: 
        - zfs_pool_check.rc == 0
        - (zfs_datasets is defined and zfs_datasets | length > 0) or (zfs_dataset_properties is defined and zfs_dataset_properties | length > 0)
    
    # WireGuard tunnel for secure NFS access (optional)
    # Only executed if wireguard_address is defined
    - role: configure_wireguard
      when: wireguard_address is defined and wireguard_address | length > 0
    
    # NFS Server Setup
    - configure_nfs_server
    
    # iSCSI Target Setup
    - configure_iscsi_target
  
  post_tasks:
    - name: Show NFS export status
      ansible.builtin.command: exportfs -v
      register: nfs_exports
      changed_when: false
    
    - name: Show iSCSI target status
      ansible.builtin.command: targetcli ls
      register: iscsi_status
      changed_when: false
    
    - name: Summary
      ansible.builtin.debug:
        msg:
          - "NAS setup completed!"
          - ""
          - "NFS Exports:"
          - "{{ nfs_exports.stdout_lines | join('\n') }}"
          - ""
          - "iSCSI Targets:"
          - "{{ iscsi_status.stdout_lines | join('\n') }}"
          - ""
          - "Next steps:"
          - "1. Create SSH key for Democratic-CSI (for user {{ zfs_k8s_user | default('zfs-k8s') }})"
          - "2. Copy SSH key to NAS: ssh-copy-id -i ~/.ssh/nas-democratic-csi.pub {{ zfs_k8s_user | default('zfs-k8s') }}@<nas-ip>"
          - "3. Create SealedSecret (see README)"
          - "4. Adjust HelmRelease configurations (zfsHostUser: {{ zfs_k8s_user | default('zfs-k8s') }}, sudoEnabled: true)"
          - "5. Activate HelmReleases"
