---
- name: Update Debian-based systems
  hosts: debian-based
  become: true
  gather_facts: true
  
  vars:
    update_cache_valid_time: 3600  # Cache für 1 Stunde gültig
    upgrade_type: "safe"  # Optionen: safe, full, dist
    reboot_if_required: false
    max_fail_percentage: 25  # Bei mehr als 25% Fehler stoppen
  
  pre_tasks:
    - name: Check if system is Debian-based
      ansible.builtin.assert:
        that: 
          - ansible_os_family == "Debian"
        msg: "This playbook can only run on Debian-based systems"
      tags: always
      
  roles:
    - role: update_debian_based_systems
      tags: [update, security]
      
  post_tasks:
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      tags: [update, reboot]
      
    - name: Reboot system if required
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Reboot triggered by Ansible after system updates"
      when: 
        - reboot_required.stat.exists | default(false)
        - reboot_if_required | bool
      tags: [update, reboot]
