---
# ===== Prometheus Exporters Setup =============================================
# Diese Datei koordiniert die Installation und Konfiguration verschiedener
# Prometheus Exporters. Jeder Exporter-Typ ist in eine separate Datei ausgelagert
# für bessere Übersichtlichkeit und Wartbarkeit.

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

# ===== Node Exporter (immer installiert) =====================================
- name: Include node_exporter tasks
  ansible.builtin.include_tasks: node_exporter.yaml

# ===== Apache Exporter (auto-detect oder manuell) ===========================
- name: Include apache_exporter tasks
  ansible.builtin.include_tasks: apache_exporter.yaml

# ===== BIND Exporter (auto-detect oder manuell) =============================
- name: Include bind_exporter tasks
  ansible.builtin.include_tasks: bind_exporter.yaml

# ===== Smartctl Exporter (nur auf echter Hardware) =========================
- name: Include smartctl_exporter tasks
  ansible.builtin.include_tasks: smartctl_exporter.yaml

# ===== MySQL/MariaDB Exporter (auto-detect oder manuell) ===================
- name: Include mysql_exporter tasks
  ansible.builtin.include_tasks: mysql_exporter.yaml

# ===== Blackbox Exporter (manuelle Aktivierung) =============================
- name: Include blackbox_exporter tasks
  ansible.builtin.include_tasks: blackbox_exporter.yaml
