---
# ===== smartctl exporter (nur auf echter Hardware) ============================
- name: Decide enable_smartctl_exporter (using has_physical_disks from pre_tasks)
  ansible.builtin.set_fact:
    _enable_smartctl_effective: "{{ (enable_smartctl_exporter | default(auto_detect_exporters)) and (has_physical_disks | default(false)) }}"

- name: Install smartctl (smartmontools)
  ansible.builtin.apt:
    name: smartmontools
    state: present
    update_cache: true
  when: _enable_smartctl_effective | bool

- name: Set smartctl exporter architecture
  ansible.builtin.set_fact:
    smartctl_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Download smartctl exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/smartctl_exporter/releases/download/v0.14.0/smartctl_exporter-0.14.0.linux-{{ smartctl_arch }}.tar.gz"
    dest: /tmp/smartctl_exporter.tar.gz
    mode: '0644'
  when: _enable_smartctl_effective | bool

- name: Extract smartctl exporter binary
  ansible.builtin.unarchive:
    src: /tmp/smartctl_exporter.tar.gz
    dest: /tmp/
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: _enable_smartctl_effective | bool

- name: Install smartctl exporter binary
  ansible.builtin.copy:
    src: /tmp/smartctl_exporter
    dest: /usr/local/bin/smartctl_exporter
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: _enable_smartctl_effective | bool

- name: Install smartctl exporter systemd service
  ansible.builtin.template:
    src: smartctl_exporter.service.j2
    dest: /etc/systemd/system/smartctl_exporter.service
    mode: "0644"
  when: _enable_smartctl_effective | bool
  notify: Daemon reload

- name: Enable and start smartctl exporter
  ansible.builtin.systemd:
    name: smartctl_exporter
    state: started
    enabled: true
  when: _enable_smartctl_effective | bool
