---
- name: Install packages
  apt: 
    name: ['icinga2-common', 'icinga2-bin', 'icinga2', 'nagios-plugins-contrib']
    state: latest
    update_cache: yes
  become: true
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int > 8 or ansible_distribution == 'Ubuntu'

- name: Install packages
  apt: 
    name: ['icinga2-common', 'icinga2-bin', 'icinga2', 'nagios-plugins-contrib']
    state: latest
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu' 

- name: configure icinga2
  become: true
  template: src=files/icinga2.conf dest=/etc/icinga2/icinga2.conf owner=root
  when: icinga2_ticket_number is defined

- name: copy registrations files for icinga2
  become: true
  template: src=files/register_icinga_node.sh dest=/tmp/register_icinga_node.sh owner=root mode=u+rwx
  when: icinga2_ticket_number is defined

- name: register icinga2 node
  become: true
  command: /tmp/register_icinga_node.sh
  when: icinga2_ticket_number is defined

- name: restart icinga2 service
  systemd:
    state: restarted
    daemon_reload: yes
    name: icinga2
