---
- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yaml"

- name: add backports repository
  become: true
  apt_repository: repo='deb {{backports_uri}} {{backports_components}}' state=present update_cache=yes
