---
- name: "Configure UFW rules for {{ port_group.name }} ports"
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ port_group.ports }}" 