---
# you also need to set non-free for the debian repos!
- name: add repo
  become: true
  apt_repository: repo='deb http://www.deb-multimedia.org stretch main non-free' state=present update_cache=yes

- name: install ffmpeg preconditions
  become: true
  apt:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  with_items:
    - deb-multimedia-keyring
    - libass-dev
    - libfaac-dev
    - libfdk-aac-dev
    - libopus-dev

