---
- stat: path=/usr/bin/sudo
  register: sudo_file

- name: install sudo + certificates
  become_method: su
  become: true
  apt: 
    name: sudo 
    state: latest 
    update_cache: yes
  when: sudo_file.stat.exists == false
