---
- stat: path=/usr/bin/sudo
  register: sudo_file

- name: install sudo + certificates
  become_method: su
  become: true
  apt: name="{{ item }}" state=latest update_cache=yes
  with_items:
   - sudo
  when: sudo_file.stat.exists == false
