---
# Mirrorbits installation settings
mirrorbits_version: "v0.6"  # Latest release version
mirrorbits_download_url: "https://github.com/etix/mirrorbits/releases/download/{{ mirrorbits_version }}/mirrorbits-{{ mirrorbits_version }}.tar.gz"
mirrorbits_bin_path: "/usr/local/bin/mirrorbits"
mirrorbits_config_dir: "/etc/mirrorbits"

# Mirrorbits configuration
mirrorbits_listen: "localhost:8080"
mirrorbits_repository_base_path: "/srv/repo"
mirrorbits_cache_dir: "/var/cache/mirrorbits"
mirrorbits_geoip_db_path: "/usr/share/GeoIP"
mirrorbits_output_mode: "auto"
mirrorbits_local_js_path: "https://cdn-m1.media.freifunk.net/mirrorbits/js"
mirrorbits_trace_file_location: "/mirrorbits/trace" 
mirrorbits_rpc_listen_address: "localhost:3390"

# Redis configuration
mirrorbits_redis_host: "127.0.0.1"
mirrorbits_redis_port: "6379"
mirrorbits_redis_password: ""
mirrorbits_redis_db: 0
mirrorbits_redis_use_sentinel: false
mirrorbits_redis_sentinel_master_name: "mirrorbits"
mirrorbits_redis_sentinels: []

# Hashing configuration
mirrorbits_use_multiple_hashes: true  # Use multiple hash algorithms instead of just one
mirrorbits_hashing_algo: "sha256"  # Used when mirrorbits_use_multiple_hashes is false
mirrorbits_enable_sha256: true
mirrorbits_enable_sha1: true
mirrorbits_enable_md5: true

# Other settings
mirrorbits_enable_trace: true
mirrorbits_enable_logging: false
mirrorbits_weight_distribution_range: 1.5
mirrorbits_disable_on_missing_file: false
mirrorbits_max_link_headers: 10

# Fallbacks configuration
mirrorbits_fallbacks:
  - url: "https://cdn-m1.media.freifunk.net/"
    country_code: "fr"
    continent_code: "eu"

# GeoIP Configuration - Leave as default for free GeoLite2 databases
# Or enter your MaxMind account details if you have a paid subscription
geoip_account_id: "0" 
geoip_license_key: "000000000000" 